version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app

  server:
    build: 
      context: ./server  
    ports:
      - "5000:5000"
    volumes:
      - .:/server
